global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'my_service'
scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'docker.host.internal:8080' ]