global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'my_service'
rule_files:
  - 'alert_rules.yml'
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093
remote_write:
  - url: localhost:3000
    basic_auth:
      username: admin
      password: magisterka2137
scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]